"""add_suite_cache_table

Revision ID: 26fcba92fc96
Revises: 9c70bee886b4
Create Date: 2025-12-26 17:54:30.599047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '26fcba92fc96'
down_revision: Union[str, None] = '9c70bee886b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suite_caches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('suite_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('ai_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('comparison', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suite_caches_id'), 'suite_caches', ['id'], unique=False)
    op.create_index(op.f('ix_suite_caches_suite_id'), 'suite_caches', ['suite_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_suite_caches_suite_id'), table_name='suite_caches')
    op.drop_index(op.f('ix_suite_caches_id'), table_name='suite_caches')
    op.drop_table('suite_caches')
    # ### end Alembic commands ###
